# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Send traces to Honeycomb
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.

exporters:
  otlp/honeycomb:
    endpoint: "https://api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"

service:
  pipelines:
    traces:
      exporters: [spanmetrics, otlp/honeycomb]
